apiVersion: v1
kind: PersistentVolume
metadata:
  name: final-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /data/final-project
    type: DirectoryOrCreate
