apiVersion: v1
kind: PersistentVolume
metadata:
  name: reclaim-demo-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /data/reclaim-demo
    type: DirectoryOrCreate
